### ISSUE TITLE
intellij font change

### ISSUE THREAD

**Issue by ozkanpakdil** [ozkanpakdil/quarkus-examples#2]
![image](https://user-images.githubusercontent.com/604405/147656696-af504ed0-d8c2-4de9-b16b-ee38b117abcb.png)

**Comment by jiayaoO3O** [comment]
I am very sorry to reply to you so late.
This is the font I use :
![image](https://user-images.githubusercontent.com/22891632/147744289-f12e28ba-0583-4862-be7c-a73dea94d0e3.png)

**Comment by ozkanpakdil** [comment]
check https://github.com/tonsky/FiraCode/issues/620 you should use different font family, try to use whatever your console has, because obviously it can show Chinese characters.
